version: '3.8'
services:
  ultralytics-cpu:
    image: ultralytics/ultralytics:latest-cpu
    ipc: host
    tty: true
    stdin_open: true
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
