version: "3.8"
services:
  yolo-server:
    build: .
    container_name: yolo-server
    ports:
      - "9500:8000"
    networks:
      - yolo-network
  web:
    build: .
    container_name: yolo-web
    ports:
      - "9501:80"
    networks:
      - yolo-network
  # ultralytics-cpu:
  #   image: ultralytics/ultralytics:latest-cpu
  #   ipc: host
  #   tty: true
  #   stdin_open: true
  #   networks:
  #     - yolo-network
networks:
  yolo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
